---
title: "Demo 6"
author: "Jussi Kauppinen 2891068547"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 6.1

\begin{equation}
\begin{split}
L(\lambda_1,..., \lambda_k) &= \prod_{i=1}^k \frac{\lambda_i^{y_i}}{y_i !} e^{-\lambda_i}\\
l(\lambda_1,..., \lambda_k) &= \sum_{i=1}^k y_i \log \lambda_i -\lambda_i - \log y_i !\\
&= \sum_{i=1}^k y_i x_i^T \beta - e^{x_i^T \beta} - \log y_i !\\
\frac{\partial}{\partial \beta}  l(\beta) &= \sum_{i=1}^k y_i x_{ij} - x_{ij} e^{x_i^T \beta}\\
\end{split}
\end{equation}

Estimating equations

$$\sum_{i=1}^k y_i x_{ij} - x_{ij} e^{x_i^T \beta} = 0$$

## Task 6.2

```{r}
library(lattice)
Bfly <- read.table("http://users.jyu.fi/~knordhau/GLM2/perhoset.txt", header=TRUE)
Bfly$habitat <- factor(Bfly$habitat, levels=c("Short", "Mixed", "Tall", "Hayfield"))

Bfly$time <- Bfly$time-1 #Shift time by 1 for better interpretations
attach(Bfly)
head(Bfly)

xyplot(Colias ~ time|habitat, group=site, data=Bfly, type="b", layout=c(2,2))

#Habitat seems to have an effect on number of butterflies.

ag <- aggregate(Colias, by=list(building), FUN=mean)

xyplot(ag$x ~ ag$Group.1, data=Bfly, type="b")

#Percentage of built in area on site seems to have negative effect on number
#of butterflies

fit1 <- glm(Colias ~ time + habitat + building, data=Bfly, family=poisson)
fit2 <- glm(Colias ~ time * habitat + building, data=Bfly, family=poisson)
anova(fit2, fit1, test="Chisq")

summary(fit2)

#It would seem like interaction between time and habitat is necessary.

ex.data1 <- data.frame(time = c(0,1,2,3,4), habitat = rep("Short", 5), building = c(0,0,0,0,0))

ex.data2 <- data.frame(time = c(0,1,2,3,4), habitat = rep("Hayfield", 5), building = c(0,0,0,0,0))

p1 <- predict(fit2, ex.data1, type="response", se.fit=TRUE)
p2 <- predict(fit2, ex.data2, type="response", se.fit=TRUE)

plot(ex.data1$time, p1$fit, type="l", col="red", ylim=c(0,25))
lines(ex.data2$time, p2$fit, type="l", col="blue")

```


## Task 6.3

```{r}
b <- coef(fit2)
b

#exp(beta0) means the expected number of butterflies in the zero case
#(short habitat, year 1, building 0)
exp(b[1])

#exp(beta1) is the percentual change in number of butterflies in one year in
#short habitat

100*(exp(b[2])-1)

#percentual difference in number of butterflies between mixed and short habitat
#when other conditions are the same is exp(beta2).
100*exp(b[3])

#Percentual change in number of butterflies when percentage of built area on
#site increases by one percent when other factors stay the same is given by

100*(exp(b[6])-1)

#Percentual change in number of butterflies in one year mixed habitat is 
#given by
100*(exp(b[2]+b[7])-1)

```


## Task 6.4

```{r}
library(MASS)

fitnb <- glm.nb(Colias ~ time * habitat + building, data=Bfly)
coef(fitnb)
coef(fit2)

#There is notable differences in all coefficients. Negative binomial model
#takes the overdispersion into account.

r <- residuals(fit2, type="pearson")
X2 <- sum(r^2)

1-pchisq(X2, 321)

eta <- log(fitted(fit2))
plot(r ~ eta)

r <- residuals(fitnb, type="pearson")
X2 <- sum(r^2)

1-pchisq(X2, 321)

eta <- log(fitted(fit2))
plot(r ~ eta)
```

## Task 6.5

```{r}
#a

WPD <- read.table ("http://users.jyu.fi/~knordhau/GLM2/verenkierto.txt", header = TRUE)
attach(WPD)
head(WPD)

#WPD$deaths100k <- ceiling(1e5*kuolleet/vaki)

library(ggplot2)
ggplot(data = WPD, aes(x = vuosi, y = ceiling(1e5*kuolleet/vaki))) +
geom_point(aes(shape = factor(sukup))) +
theme_bw()

#b

fitd <- glm(kuolleet ~ I(vuosi-1970) * sukup + offset(log(vaki)), data=WPD, family="poisson")

summary(fitd)

b <- coef(fitd)

#Expected number of male deaths per 100k persons at working age
#in 1970

1e5*exp(b[1])

1e5*exp(confint(fitd))[1,]

#Percentual change in one year.

100*(exp(b[2])-1)
100*(exp(confint(fitd))[2,]-1)

new.data <- data.frame(vuosi=vuosi, sukup=sukup, vaki=1e5)

pred <- predict(fitd, new.data, type="response")

d <- data.frame(intensiteetti = c(1e5 * kuolleet / vaki, pred),
                vuosi = vuosi, sukup = factor(sukup, labels=c("Mies", "Nainen")),
                type = rep(c("Havaittu", "Mallinnettu"), each = nrow(WPD)))

ggplot(data=d, aes(x=vuosi, y=intensiteetti))+
  geom_line(aes(linetype=sukup, colour=type))+
  geom_point(aes(shape=sukup, colour=type), position = position_jitter(1,0, seed=1))+
  theme_classic()

```


## Task 6.6

```{r}
new.data2 <- data.frame(sukup = rep(0:1, 7), vuosi = rep(2015:2021, each=2), vaki=1e5)

pred2 <- predict(fitd, new.data2, type="response", se.fit = TRUE)

new.data2$ennuste <- pred2$fit

new.data2$ala <- pred2$fit - qnorm(0.975) * sqrt(pred2$fit + pred2$se.fit^2)

new.data2$yla <- pred2$fit + qnorm(0.975) * sqrt(pred2$fit + pred2$se.fit^2)

new.data2

```

