---
title: "Bayes_HT"
author: "Jussi Kauppinen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
siemenluku <- 2891068547 # LAITA TÄHÄN OPISKELIJANUMEROSI
# jos set.seed(siemenluku antaa virheilmoituksen), 
# vaihda siemenluvuksi opiskelijanumerosi neljä viimeistä numeroa
set.seed(siemenluku)
library("rlang")
library("haven")
library("tidyr")
library("dplyr")

d <- read_spss("daF2076e.por") |> 
  select(
    arvosana = K82,
    sukupuoli = T3,
    koulutustaso = BV2_1,
    tulot = BV4_1,
    ITPA = L17,
  ) |> 
  mutate(
    sukupuoli = factor(sukupuoli, labels = c("Mies", "Nainen")),
    koulutustaso = recode_factor(
      factor(koulutustaso),
      "2" = "Korkeintaan toisen asteen koulutus",
      "3" = "Korkeintaan toisen asteen koulutus",
      "4" = "Korkeintaan toisen asteen koulutus",
      "5" = "Alempi korkeakouluaste tai alin korkea-aste",
      "6" = "Alempi korkeakouluaste tai alin korkea-aste",
      "7" = "Ylempi korkeakouluaste",
      "8" = "Ylempi korkeakouluaste"
    )
  ) |> 
  slice(sample(seq_len(n()), size = 300)) |> 
  # käytetään vain täysiä havaintorivejä yksinkertaisuuden vuoksi
  drop_na()
```
